export const projects = [
  {
    name: "Exclusive E-commerce",
    type: "web_development",
    image: "/assets/web_development_1.png",
    tech: ["React", "HTML", "Javascript"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Memory Match Games",
    type: "web_development",
    image: "/assets/web_development_2.png",
    tech: ["Javascript", "CSS", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Interior Company Website",
    type: "web_development",
    image: "/assets/web_development_3.png",
    tech: ["TailwindCSS", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Luxespace",
    type: "web_development",
    image: "/assets/web_development_4.png",
    tech: ["React", "TailwindCSS"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Live stock Calc",
    type: "web_development",
    image: "/assets/web_development_5.png",
    tech: ["NextJS", "NodeJs", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "HealtyDOC",
    type: "web_development",
    image: "/assets/web_development_6.png",
    tech: ["NextJS", "NodeJs", "Prisma"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "RFM Analysist",
    type: "data_analysist",
    image: "/assets/data_analysis1.png",
    tech: ["Python", "Jupyter Notebook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "AirBnB Bangkok",
    type: "data_analysist",
    image: "/assets/data_analysis2.png",
    tech: ["Python", "Tableau"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Market Analysist",
    type: "data_analysist",
    image: "/assets/data_analysis3.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Customer Churn Predict",
    type: "machine_learning",
    image: "/assets/machine_learning_1.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Recommendation System",
    type: "machine_learning",
    image: "/assets/machine_learning_2.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },

  {
    name: "KFC Revamp",
    type: "ui_ux",
    image: "/assets/ui_ux_1.png",
    tech: ["Figma", "Adobe"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Company Landingpage",
    type: "ui_ux",
    image: "/assets/ui_ux_2.png",
    tech: ["Figma"],
    description: "",
    link: "",
    github: "",
  },
];
