export const projects = [
  {
    name: "Food blog Website Flavoriz",
    type: "web_development",
    image: "/assets/flavoriz.png",
    tech: ["Vue.js", "HTML", "Javascript"],
    features: [],
    description:
      "A lightweight and user-friendly food recipe web application built using Vue.js. This project fetches recipe data from an API, providing users with an intuitive way to browse, search, and view detailed recipes. Designed with modern aesthetics, the app leverages Tailwind CSS and shadcn for responsive and visually appealing UI components.",
    link: "https://flavorizefood.netlify.app/",
    github: "https://github.com/fiqrioemry/Vue-Food-Recipe-Web-App",
  },
  {
    name: "Memory Match Games",
    type: "web_development",
    image: "/assets/web_development_2.png",
    tech: ["Javascript", "CSS", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Interior Company Website",
    type: "web_development",
    image: "/assets/web_development_3.png",
    tech: ["TailwindCSS", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Luxespace",
    type: "web_development",
    image: "/assets/web_development_4.png",
    tech: ["React", "TailwindCSS"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Live stock Calc",
    type: "web_development",
    image: "/assets/web_development_5.png",
    tech: ["NextJS", "NodeJs", "HTML"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "HealtyDOC",
    type: "web_development",
    image: "/assets/web_development_6.png",
    tech: ["NextJS", "NodeJs", "Prisma"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "RFM Analysist",
    type: "data_analysist",
    image: "/assets/data_analysis1.png",
    tech: ["Python", "Jupyter Notebook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "AirBnB Bangkok",
    type: "data_analysist",
    image: "/assets/data_analysis2.png",
    tech: ["Python", "Tableau"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Market Analysist",
    type: "data_analysist",
    image: "/assets/data_analysis3.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Customer Churn Predict",
    type: "machine_learning",
    image: "/assets/machine_learning_1.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Recommendation System",
    type: "machine_learning",
    image: "/assets/machine_learning_2.png",
    tech: ["Jupyter Nootbook"],
    description: "",
    link: "",
    github: "",
  },

  {
    name: "KFC Revamp",
    type: "ui_ux",
    image: "/assets/ui_ux_1.png",
    tech: ["Figma", "Adobe"],
    description: "",
    link: "",
    github: "",
  },
  {
    name: "Company Landingpage",
    type: "ui_ux",
    image: "/assets/ui_ux_2.png",
    tech: ["Figma"],
    description: "",
    link: "",
    github: "",
  },
];
